
_REGISTERS_TREX_FIFTY = {
    "time_year_month": {'address': 4357, 'name': 'Time: Year-Month', 'precision': 0, 'index': 99, 'state_class': 'measurement'},
    "time_day_time": {'address': 4358, 'name': 'Time: Day-Time', 'precision': 0, 'index': 99, 'state_class': 'measurement'},
    "time_minutes_seconds": {'address': 4359, 'name': 'Time: minutes-seconds', 'precision': 0, 'index': 99, 'state_class': 'measurement'},
    "time_week": {'address': 4360, 'name': 'Time: Week', 'precision': 0, 'index': 99, 'state_class': 'measurement'},
    "alarm_codes": {'address': 4361, 'name': 'Alarm codes', 'precision': 0, 'index': 5, 'state_class': 'measurement'},
    "fault_codes": {'address': 4362, 'name': 'Fault codes', 'precision': 0, 'index': 5, 'state_class': 'measurement'},
    "pv1_voltage": {'address': 4376, 'name': 'PV1 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "pv2_voltage": {'address': 4377, 'name': 'PV2 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "pv3_voltage": {'address': 4378, 'name': 'PV3 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "pv4_voltage": {'address': 4379, 'name': 'PV4 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "mppt1_current": {'address': 4380, 'name': 'MPPT1 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "mppt2_current": {'address': 4381, 'name': 'MPPT2 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "mppt3_current": {'address': 4382, 'name': 'MPPT3 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "mppt4_current": {'address': 4383, 'name': 'MPPT4 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_home_load_power": {'address': 4384, 'name': 'Phase A home load power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_home_load_power": {'address': 4385, 'name': 'Phase B home load power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_home_load_power": {'address': 4386, 'name': 'Phase C home load power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "pv1_power": {'address': 4392, 'name': 'PV1 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "pv2_power": {'address': 4393, 'name': 'PV2 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "pv3_power": {'address': 4394, 'name': 'PV3 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "pv4_power": {'address': 4395, 'name': 'PV4 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "bat1_voltage": {'address': 4396, 'name': 'Bat1 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "bat2_voltage": {'address': 4397, 'name': 'Bat2 voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "bat1_current": {'address': 4400, 'name': 'Bat1 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "bat1_power": {'address': 4401, 'name': 'Bat1 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "bat2_current": {'address': 4402, 'name': 'Bat2 current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "bat2_power": {'address': 4403, 'name': 'Bat2 power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "bat1_insulation_resistance": {'address': 4404, 'name': 'Bat1+ insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},
    "bat1_insulation_resistance_1": {'address': 4405, 'name': 'Bat1- insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},  # Note: key dupes fixed with _1
    "bat2_insulation_resistance": {'address': 4406, 'name': 'Bat2+ insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},
    "bat2_insulation_resistance_1": {'address': 4407, 'name': 'Bat2- insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},
    "bat1_soc": {'address': 4408, 'name': 'Bat1 SOC', 'precision': 1, 'index': 1, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "bat1_soh": {'address': 4409, 'name': 'Bat1 SOH', 'precision': 1, 'index': 1, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "bat1_capacity": {'address': 4410, 'name': 'Bat1 Capacity', 'precision': 0, 'index': 0, 'unit': 'AH', 'state_class': 'measurement'},
    "bat2_soc": {'address': 4411, 'name': 'Bat2 SOC', 'precision': 1, 'index': 1, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "bat2_soh": {'address': 4412, 'name': 'Bat2 SOH', 'precision': 1, 'index': 1, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "bat2_capacity": {'address': 4413, 'name': 'Bat2 Capacity', 'precision': 0, 'index': 0, 'unit': 'AH', 'state_class': 'measurement'},
    "bus_voltage": {'address': 4414, 'name': 'Bus voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "bus_voltage_1": {'address': 4415, 'name': 'Bus+ voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "bus_voltage_2": {'address': 4416, 'name': 'Bus- voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "balance_current": {'address': 4417, 'name': 'Balance current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "bus_insulation_resistance": {'address': 4418, 'name': 'Bus+ insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},
    "bus_insulation_resistance_1": {'address': 4419, 'name': 'Bus- insulation resistance', 'precision': 0, 'index': 0, 'unit': 'KΩ', 'state_class': 'measurement'},
    "boost_temperature": {'address': 4420, 'name': 'Boost temperature', 'precision': 0, 'index': 3, 'unit': '°C', 'device_class': 'temperature', 'state_class': 'measurement'},
    "inverter_temperature": {'address': 4421, 'name': 'Inverter temperature', 'precision': 0, 'index': 3, 'unit': '°C', 'device_class': 'temperature', 'state_class': 'measurement'},
    "ambient_temperature": {'address': 4422, 'name': 'Ambient temperature', 'precision': 0, 'index': 3, 'unit': '°C', 'device_class': 'temperature', 'state_class': 'measurement'},
    "leakage_current": {'address': 4425, 'name': 'Leakage current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_generator_current": {'address': 4426, 'name': 'Phase A generator current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_generator_current": {'address': 4427, 'name': 'Phase B generator current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_generator_current": {'address': 4428, 'name': 'Phase C generator current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_generator_voltage": {'address': 4429, 'name': 'Phase A generator voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_b_generator_voltage": {'address': 4430, 'name': 'Phase B generator voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_c_generator_voltage": {'address': 4431, 'name': 'Phase C generator voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_a_grid_voltage": {'address': 4432, 'name': 'Phase A grid voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_b_grid_voltage": {'address': 4433, 'name': 'Phase B grid voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_c_grid_voltage": {'address': 4434, 'name': 'Phase C grid voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_a_inverter_voltage": {'address': 4435, 'name': 'Phase A inverter voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_b_inverter_voltage": {'address': 4436, 'name': 'Phase B inverter voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_c_inverter_voltage": {'address': 4437, 'name': 'Phase C inverter voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_a_load_voltage": {'address': 4438, 'name': 'Phase A load voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_b_load_voltage": {'address': 4439, 'name': 'Phase B load voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_c_load_voltage": {'address': 4440, 'name': 'Phase C load voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_a_ct_current": {'address': 4441, 'name': 'Phase A CT current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_ct_current": {'address': 4442, 'name': 'Phase B CT current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_ct_current": {'address': 4443, 'name': 'Phase C CT current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_grid_current": {'address': 4444, 'name': 'Phase A grid current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_grid_current": {'address': 4445, 'name': 'Phase B grid current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_grid_current": {'address': 4446, 'name': 'Phase C grid current', 'precision': 1, 'index': 8, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_inverter_current": {'address': 4447, 'name': 'Phase A inverter current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_inverter_current": {'address': 4448, 'name': 'Phase B inverter current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_inverter_current": {'address': 4449, 'name': 'Phase C inverter current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_load_current": {'address': 4450, 'name': 'Phase A load current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_load_current": {'address': 4451, 'name': 'Phase B load current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_load_current": {'address': 4452, 'name': 'Phase C load current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_a_inverter_dc_voltage_value": {'address': 4453, 'name': 'Phase A inverter DC voltage value', 'precision': 0, 'index': 3, 'unit': 'mV', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_b_inverter_dc_voltage_value": {'address': 4454, 'name': 'Phase B inverter DC voltage value', 'precision': 0, 'index': 3, 'unit': 'mV', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_c_inverter_dc_voltage_value": {'address': 4455, 'name': 'Phase C inverter DC voltage value', 'precision': 0, 'index': 3, 'unit': 'mV', 'device_class': 'voltage', 'state_class': 'measurement'},
    "phase_a_inverter_dc_current_value": {'address': 4456, 'name': 'Phase A inverter DC current value', 'precision': 0, 'index': 3, 'unit': 'mA', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_b_inverter_dc_current_value": {'address': 4457, 'name': 'Phase B inverter DC current value', 'precision': 0, 'index': 3, 'unit': 'mA', 'device_class': 'current', 'state_class': 'measurement'},
    "phase_c_inverter_dc_current_value": {'address': 4458, 'name': 'Phase C inverter DC current value', 'precision': 0, 'index': 3, 'unit': 'mA', 'device_class': 'current', 'state_class': 'measurement'},
    "n_n_voltage": {'address': 4459, 'name': 'N-N voltage', 'precision': 1, 'index': 8, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "generator_frequency": {'address': 4460, 'name': 'Generator frequency', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid_frequency": {'address': 4461, 'name': 'Grid frequency', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "inverter_frequency": {'address': 4462, 'name': 'Inverter frequency', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "load_frequency": {'address': 4463, 'name': 'Load frequency', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "phase_a_generator_active_power": {'address': 4464, 'name': 'Phase A generator active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_generator_active_power": {'address': 4465, 'name': 'Phase B generator active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_generator_active_power": {'address': 4466, 'name': 'Phase C generator active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_a_grid_active_power": {'address': 4467, 'name': 'Phase A grid active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_grid_active_power": {'address': 4468, 'name': 'Phase B grid active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_grid_active_power": {'address': 4469, 'name': 'Phase C grid active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_a_inverter_active_power": {'address': 4470, 'name': 'Phase A inverter active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_inverter_active_power": {'address': 4471, 'name': 'Phase B inverter active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_inverter_active_power": {'address': 4472, 'name': 'Phase C inverter active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_a_load_active_power": {'address': 4473, 'name': 'Phase A load active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_load_active_power": {'address': 4474, 'name': 'Phase B load active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_load_active_power": {'address': 4475, 'name': 'Phase C load active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_a_load_apparent_power": {'address': 4476, 'name': 'Phase A load apparent power', 'precision': 1, 'index': 8, 'unit': 'kVA', 'device_class': 'apparent_power', 'state_class': 'measurement'},  # Custom: apparent_power
    "phase_b_load_apparent_power": {'address': 4477, 'name': 'Phase B load apparent power', 'precision': 1, 'index': 8, 'unit': 'kVA', 'device_class': 'apparent_power', 'state_class': 'measurement'},
    "phase_c_load_apparent_power": {'address': 4478, 'name': 'Phase C load apparent power', 'precision': 1, 'index': 8, 'unit': 'kVA', 'device_class': 'apparent_power', 'state_class': 'measurement'},
    "phase_a_load_percentage": {'address': 4479, 'name': 'Phase A load percentage', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "phase_b_load_percentage": {'address': 4480, 'name': 'Phase B load percentage', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "phase_c_load_percentage": {'address': 4481, 'name': 'Phase C load percentage', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "phase_a_ct_active_power": {'address': 4482, 'name': 'Phase A CT active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_b_ct_active_power": {'address': 4483, 'name': 'Phase B CT active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_c_ct_active_power": {'address': 4484, 'name': 'Phase C CT active power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "phase_a_grid_power_factor": {'address': 4485, 'name': 'Phase A Grid Power Factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},  # Custom: power_factor
    "phase_b_grid_power_factor": {'address': 4486, 'name': 'Phase B Grid Power Factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},
    "phase_c_grid_power_factor": {'address': 4487, 'name': 'Phase C Grid Power Factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},
    "phase_a_inverter_power_factor": {'address': 4488, 'name': 'Phase A inverter power factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},
    "phase_b_inverter_power_factor": {'address': 4489, 'name': 'Phase B inverter power factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},
    "phase_c_inverter_power_factor": {'address': 4490, 'name': 'Phase C inverter power factor (0.01)', 'precision': 2, 'index': 9, 'device_class': 'power_factor', 'state_class': 'measurement'},
    "microinverter_total_energy": {'address': 4492, 'name': 'Microinverter Total Energy High （0.1KWh）', 'precision': 1, 'index': 8, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "generator_start_signal": {'address': 4497, 'name': 'Generator start signal', 'precision': 0, 'index': 3, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},  # From old pattern
    "total_generator_power": {'address': 4498, 'name': 'Total generator power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "total_load_power": {'address': 4499, 'name': 'Total load power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "total_grid_power": {'address': 4500, 'name': 'Total grid power', 'precision': 1, 'index': 8, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "pv1_day_energy": {'address': 4529, 'name': 'PV1 Day Energy（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "pv1_month_energy": {'address': 4530, 'name': 'PV1 Month Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv1_year_energy": {'address': 4532, 'name': 'PV1 Year Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv2_day_energy": {'address': 4534, 'name': 'PV2 Day Energy（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "pv2_month_energy": {'address': 4535, 'name': 'PV2 Month Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv2_year_energy": {'address': 4537, 'name': 'PV2 Year Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv3_day_energy": {'address': 4539, 'name': 'PV3 Day Energy（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "pv3_month_energy": {'address': 4540, 'name': 'PV3 Month Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv3_year_energy": {'address': 4542, 'name': 'PV3 Year Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv4_day_energy": {'address': 4544, 'name': 'PV4 Day Energy（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "pv4_month_energy": {'address': 4545, 'name': 'PV4 Month Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv4_year_energy": {'address': 4547, 'name': 'PV4 Year Energy High（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "pv_total_energy": {'address': 4549, 'name': 'PV Total Energy High', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat1_day_charge_energy": {'address': 4551, 'name': 'Bat1 Day Charge Energy（0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "bat1_month_charge_energy": {'address': 4552, 'name': 'Bat1 Month Charge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat1_year_charge_energy": {'address': 4554, 'name': 'Bat1 Year Charge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat1_day_discharge_energy": {'address': 4556, 'name': 'Bat1 Day Discharge Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "bat1_month_discharge_energy": {'address': 4557, 'name': 'Bat1 Month Discharge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat1_year_discharge_energy": {'address': 4559, 'name': 'Bat1 Year Discharge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat2_day_charge_energy": {'address': 4561, 'name': 'BAT2 Day Charge Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "bat2_month_charge_energy": {'address': 4562, 'name': 'BAT2 Month Charge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat2_year_charge_energy": {'address': 4564, 'name': 'BAT2 Year Charge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat2_day_discharge_energy": {'address': 4566, 'name': 'BAT2 Day Discharge Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "bat2_month_discharge_energy": {'address': 4567, 'name': 'BAT2 Month Discharge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "bat2_year_discharge_energy": {'address': 4569, 'name': 'BAT2 Year Discharge Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "grid_day_cost_energy": {'address': 4571, 'name': 'Grid Day Cost Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "grid_month_cost_energy": {'address': 4572, 'name': 'Grid Month Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "grid_year_cost_energy": {'address': 4574, 'name': 'Grid Year Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "grid_day_feed_energy": {'address': 4576, 'name': 'Grid Day Feed Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "grid_month_feed_energy": {'address': 4577, 'name': 'Grid Month Feed Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "grid_year_feed_energy": {'address': 4579, 'name': 'Grid Year Feed Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "load_day_cost_energy": {'address': 4581, 'name': 'Load Day Cost Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "load_month_cost_energy": {'address': 4582, 'name': 'Load Month Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "load_year_cost_energy": {'address': 4584, 'name': 'Load Year Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "generator_day_cost_energy": {'address': 4586, 'name': 'Generator Day Cost Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "generator_month_cost_energy": {'address': 4587, 'name': 'Generator Month Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "generator_year_cost_energy": {'address': 4589, 'name': 'Generator Year Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "microinverter_day_cost_energy": {'address': 4591, 'name': 'Microinverter Day Cost Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "microinverter_month_cost_energy": {'address': 4592, 'name': 'Microinverter Month Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "microinverter_year_cost_energy": {'address': 4594, 'name': 'Microinverter Year Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "homeload_day_cost_energy": {'address': 4596, 'name': 'Homeload Day Cost Energy （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing'},
    "homeload_month_cost_energy": {'address': 4597, 'name': 'Homeload Month Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    "homeload_year_cost_energy": {'address': 4599, 'name': 'Homeload Year Cost Energy High （0.1KWh）', 'precision': 1, 'index': 1, 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'size': 2, 'endian': 'big'},
    # the 8k range
    "battery_1_max_charge_current": {'address': 8471, 'name': 'Battery 1 MAX charge current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "battery_1_max_discharge_current": {'address': 8472, 'name': 'Battery 1 MAX discharge current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "grid_start_signal": {'address': 8477, 'name': 'Grid start signal', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "generator_cooldown_time": {'address': 8478, 'name': 'Generator cooldown time', 'precision': 1, 'index': 1, 'unit': 'hours', 'state_class': 'measurement'},
    "generator_forced_to_run": {'address': 8479, 'name': 'Generator forced to run', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "soc_of_the_grid_auto_start_charge": {'address': 8480, 'name': 'SOC of the Grid Auto Start Charge', 'precision': 0, 'index': 0, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "soc_of_the_grid_exit_charge": {'address': 8481, 'name': 'SOC of the Grid Exit Charge', 'precision': 0, 'index': 0, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "soc_of_the_gen_auto_start_charge": {'address': 8482, 'name': 'SOC of the GEN Auto Start Charge', 'precision': 0, 'index': 0, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "soc_of_the_gen_exit_charge": {'address': 8483, 'name': 'SOC of the GEN Exit Charge', 'precision': 0, 'index': 0, 'device_class': 'battery', 'state_class': 'measurement','unit': '%'},
    "grid_charge_current": {'address': 8484, 'name': 'Grid Charge Current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "gen_charge_current": {'address': 8485, 'name': 'GEN Charge Current', 'precision': 1, 'index': 1, 'unit': 'A', 'device_class': 'current', 'state_class': 'measurement'},
    "gen_start_signal": {'address': 8486, 'name': 'GEN Start Signal', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "grid_charge_enable": {'address': 8487, 'name': 'Grid Charge Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "gen_charge_enable": {'address': 8488, 'name': 'GEN Charge Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "gen_max_run_time": {'address': 8489, 'name': 'GEN Max Run Time', 'precision': 1, 'index': 1, 'unit': 'hours', 'state_class': 'measurement'},
    "voltage_of_the_grid_auto_start_charge": {'address': 8490, 'name': 'Voltage of the Grid Auto Start Charge', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_grid_exit_charge": {'address': 8491, 'name': 'Voltage of the Grid Exit Charge', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_gen_auto_start_charge": {'address': 8492, 'name': 'Voltage of the GEN Auto Start Charge', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_gen_exit_charge": {'address': 8493, 'name': 'Voltage of the GEN Exit Charge', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "battery_float_charge_voltage": {'address': 8500, 'name': 'Battery float charge voltage', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_battery_restart": {'address': 8503, 'name': 'Voltage of the Battery Restart', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_battery_low_alarm": {'address': 8504, 'name': 'Voltage of the Battery Low Alarm', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "voltage_of_the_battery_shutdown": {'address': 8505, 'name': 'Voltage of the Battery Shutdown', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "soc_of_the_battery_restart": {'address': 8506, 'name': 'SOC of the Battery Restart', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "soc_of_the_battery_low_alarm": {'address': 8507, 'name': 'SOC of the Battery Low Alarm', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "soc_of_the_battery_shutdown": {'address': 8508, 'name': 'SOC of the Battery Shutdown', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "system_mode": {'address': 8516, 'name': 'System Mode', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Selling Mode', 'Zero Export To Load', 'Zero Export To CT']},
    "zero_export_to_load_sell_enable": {'address': 8517, 'name': 'Zero Export To Load Sell Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "zero_export_to_ct_sell_enable": {'address': 8518, 'name': 'Zero Export To CT Sell Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "max_export_power_to_grid": {'address': 8519, 'name': 'Max-Export power to grid', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "grid_peak_shaving_enable": {'address': 8520, 'name': 'Grid Peak Shaving Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "grid_peak_shaving_power": {'address': 8521, 'name': 'Grid Peak Shaving Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'type': 'number', 'device_class': 'power', 'state_class': 'measurement'},
    "zero_export_power": {'address': 8522, 'name': 'Zero-export Power', 'precision': 0, 'index': 3, 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement'},
    "zero_export_mode_selection": {'address': 8523, 'name': 'Zero-export mode selection', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['CT', 'Meter']},
    "energy_priority": {'address': 8525, 'name': 'Energy priority', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Bat First', 'Load First']},
    "grid_port_balance_enable": {'address': 8542, 'name': 'Grid Port Balance Enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "back_up_delay": {'address': 8544, 'name': 'Back Up delay', 'precision': 0, 'index': 0, 'unit': 'ms', 'state_class': 'measurement'},
    "load_relay_break": {'address': 8548, 'name': 'Load Relay Break', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "back_up_delay_time": {'address': 8549, 'name': 'Back Up Delay time', 'precision': 0, 'index': 0, 'unit': 's', 'state_class': 'measurement'},
    "gridnormalconnecthighvolt": {'address': 8624, 'name': 'GridNormalConnectHighVolt', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gridnormalconnectlowvolt": {'address': 8625, 'name': 'GridNormalConnectLowVolt', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gridnormalconnecthighfreq": {'address': 8626, 'name': 'GridNormalConnectHighFreq', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gridnormalconnectlowfreq": {'address': 8627, 'name': 'GridNormalConnectLowFreq', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gridrecconnecthighvolt": {'address': 8628, 'name': 'GridRecConnectHighVolt', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gridrecconnectlowvolt": {'address': 8629, 'name': 'GridRecConnectLowVolt', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gridrecconnecthighfreq": {'address': 8630, 'name': 'GridRecConnectHighFreq', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gridrecconnectlowfreq": {'address': 8631, 'name': 'GridRecConnectLowFreq', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid1ovvalue": {'address': 8666, 'name': 'Grid1OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid1ovtime": {'address': 8667, 'name': 'Grid1OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid2ovvalue": {'address': 8668, 'name': 'Grid2OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid2ovtime": {'address': 8669, 'name': 'Grid2OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid3ovvalue": {'address': 8670, 'name': 'Grid3OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid3ovtime": {'address': 8671, 'name': 'Grid3OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid4ovvalue": {'address': 8672, 'name': 'Grid4OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid4ovtime": {'address': 8673, 'name': 'Grid4OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid5ovvalue": {'address': 8674, 'name': 'Grid5OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid5ovtime": {'address': 8675, 'name': 'Grid5OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid1uvvalue": {'address': 8676, 'name': 'Grid1UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid1uvtime": {'address': 8677, 'name': 'Grid1UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid2uvvalue": {'address': 8678, 'name': 'Grid2UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid2uvtime": {'address': 8679, 'name': 'Grid2UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid3uvvalue": {'address': 8680, 'name': 'Grid3UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid3uvtime": {'address': 8681, 'name': 'Grid3UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid4uvvalue": {'address': 8682, 'name': 'Grid4UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid4uvtime": {'address': 8683, 'name': 'Grid4UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid5uvvalue": {'address': 8684, 'name': 'Grid5UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "grid5uvtime": {'address': 8685, 'name': 'Grid5UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gridvunbalanceprotectvalue": {'address': 8686, 'name': 'GridVUnbalanceProtectValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gridvunbalanceprotecttime": {'address': 8687, 'name': 'GridVUnbalanceProtectTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid1ofvalue": {'address': 8688, 'name': 'Grid1OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid1oftime": {'address': 8689, 'name': 'Grid1OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid2ofvalue": {'address': 8690, 'name': 'Grid2OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid2oftime": {'address': 8691, 'name': 'Grid2OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid3ofvalue": {'address': 8692, 'name': 'Grid3OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid3oftime": {'address': 8693, 'name': 'Grid3OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid4ofvalue": {'address': 8694, 'name': 'Grid4OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid4oftime": {'address': 8695, 'name': 'Grid4OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid5ofvalue": {'address': 8696, 'name': 'Grid5OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid5oftime": {'address': 8697, 'name': 'Grid5OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid1ufvalue": {'address': 8698, 'name': 'Grid1UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid1uftime": {'address': 8699, 'name': 'Grid1UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid2ufvalue": {'address': 8700, 'name': 'Grid2UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid2uftime": {'address': 8701, 'name': 'Grid2UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid3ufvalue": {'address': 8702, 'name': 'Grid3UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid3uftime": {'address': 8703, 'name': 'Grid3UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid4ufvalue": {'address': 8704, 'name': 'Grid4UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid4uftime": {'address': 8705, 'name': 'Grid4UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "grid5ufvalue": {'address': 8706, 'name': 'Grid5UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "grid5uftime": {'address': 8707, 'name': 'Grid5UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "10minovpenable": {'address': 8708, 'name': '10minOVPEnable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "10minovpvalue": {'address': 8709, 'name': '10minOVPValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "10minovptime": {'address': 8710, 'name': '10minOVPTime', 'precision': 0, 'index': 0, 'unit': 's', 'state_class': 'measurement'},
    "eco_timeofuse": {'address': 8711, 'name': 'ECO_TimeOfUse', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "eco_effectiveweek": {'address': 8712, 'name': 'ECO_EffectiveWeek', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_1_grid_charge_enable": {'address': 8713, 'name': 'ECO1_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_1_gen_charge_enable": {'address': 8714, 'name': 'ECO1_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_1_start_time": {'address': 8715, 'name': 'ECO1_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_1_stop_time": {'address': 8716, 'name': 'ECO1_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_1_voltage": {'address': 8717, 'name': 'ECO1_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_1_soc": {'address': 8718, 'name': 'ECO1_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_1_power": {'address': 8719, 'name': 'ECO1_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "econ_rule_2_grid_charge_enable": {'address': 8720, 'name': 'ECO2_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_2_gen_charge_enable": {'address': 8721, 'name': 'ECO2_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_2_start_time": {'address': 8722, 'name': 'ECO2_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_2_stop_time": {'address': 8723, 'name': 'ECO2_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_2_voltage": {'address': 8724, 'name': 'ECO2_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_2_soc": {'address': 8725, 'name': 'ECO2_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_2_power": {'address': 8726, 'name': 'ECO2_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "econ_rule_3_grid_charge_enable": {'address': 8727, 'name': 'ECO3_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_3_gen_charge_enable": {'address': 8728, 'name': 'ECO3_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_3_start_time": {'address': 8729, 'name': 'ECO3_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_3_stop_time": {'address': 8730, 'name': 'ECO3_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_3_voltage": {'address': 8731, 'name': 'ECO3_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_3_soc": {'address': 8732, 'name': 'ECO3_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_3_power": {'address': 8733, 'name': 'ECO3_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "econ_rule_4_grid_charge_enable": {'address': 8734, 'name': 'ECO4_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_4_gen_charge_enable": {'address': 8735, 'name': 'ECO4_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_4_start_time": {'address': 8736, 'name': 'ECO4_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_4_stop_time": {'address': 8737, 'name': 'ECO4_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_4_voltage": {'address': 8738, 'name': 'ECO4_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_4_soc": {'address': 8739, 'name': 'ECO4_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_4_power": {'address': 8740, 'name': 'ECO4_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "econ_rule_5_grid_charge_enable": {'address': 8741, 'name': 'ECO5_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_5_gen_charge_enable": {'address': 8742, 'name': 'ECO5_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_5_start_time": {'address': 8743, 'name': 'ECO5_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_5_stop_time": {'address': 8744, 'name': 'ECO5_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_5_voltage": {'address': 8745, 'name': 'ECO5_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_5_soc": {'address': 8746, 'name': 'ECO5_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_5_power": {'address': 8747, 'name': 'ECO5_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "econ_rule_6_grid_charge_enable": {'address': 8748, 'name': 'ECO6_grid_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_6_gen_charge_enable": {'address': 8749, 'name': 'ECO6_gen_charge_enable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "econ_rule_6_start_time": {'address': 8750, 'name': 'ECO6_start_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_6_stop_time": {'address': 8751, 'name': 'ECO6_stop_time', 'precision': 0, 'index': 0, 'type': 'time8bit', 'state_class': 'measurement'},
    "econ_rule_6_voltage": {'address': 8752, 'name': 'ECO6_Volt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "econ_rule_6_soc": {'address': 8753, 'name': 'ECO6_SOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "econ_rule_6_power": {'address': 8754, 'name': 'ECO6_Power', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "genmode": {'address': 8759, 'name': 'GenMode', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Generator', 'Smart Load', 'Micro Inv']},
    "geninputratepower": {'address': 8760, 'name': 'GenInputRatePower', 'precision': 1, 'index': 1, 'unit': 'kW', 'device_class': 'power', 'state_class': 'measurement'},
    "genpowerpeakshaving": {'address': 8761, 'name': 'GenPowerPeakShaving', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "genconnecttogridportenable": {'address': 8762, 'name': 'GenConnectToGridPortEnable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "smartloadcloseenable": {'address': 8763, 'name': 'SmartLoadCloseEnable', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "smartload_closebatvolt": {'address': 8764, 'name': 'SmartLoad_CloseBatVolt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "smartload_openbatvolt": {'address': 8765, 'name': 'SmartLoad_OpenBatVolt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "smartload_closesoc": {'address': 8766, 'name': 'SmartLoad_CloseSOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "smartload_opensoc": {'address': 8767, 'name': 'SmartLoad_OpenSOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "ac_couple_frz_high": {'address': 8768, 'name': 'AC_Couple_Frz_High', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "ml_export_to_grid_cutoff": {'address': 8769, 'name': 'Ml_export_to_Grid_cutoff', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "ac_couple_onside": {'address': 8770, 'name': 'AC_Couple_OnSide', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Grid', 'Load']},
    "micro_closebatvolt": {'address': 8771, 'name': 'Micro_CloseBatVolt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "micro_openbatvolt": {'address': 8772, 'name': 'Micro_OpenBatVolt', 'precision': 1, 'index': 1, 'unit': 'V', 'device_class': 'voltage', 'state_class': 'measurement'},
    "micro_closesoc": {'address': 8773, 'name': 'Micro_CloseSOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "micro_opensoc": {'address': 8774, 'name': 'Micro_OpenSOC', 'precision': 0, 'index': 0, 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement'},
    "smartload_closeminpvpower": {'address': 8775, 'name': 'SmartLoad_CloseMinPvPower', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "smartload_offgridimmediatelyoff": {'address': 8776, 'name': 'SmartLoad_offGridimmediatelyOff', 'precision': 0, 'index': 0, 'state_class': 'measurement', 'type': 'select', 'options': ['Disabled', 'Enabled']},
    "gen1ovvalue": {'address': 8778, 'name': 'Gen1OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gen1ovtime": {'address': 8779, 'name': 'Gen1OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen2ovvalue": {'address': 8780, 'name': 'Gen2OVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gen2ovtime": {'address': 8781, 'name': 'Gen2OVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen1uvvalue": {'address': 8782, 'name': 'Gen1UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gen1uvtime": {'address': 8783, 'name': 'Gen1UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen2uvvalue": {'address': 8784, 'name': 'Gen2UVValue', 'precision': 0, 'index': 0, 'unit': '%', 'state_class': 'measurement'},
    "gen2uvtime": {'address': 8785, 'name': 'Gen2UVTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen1ofvalue": {'address': 8786, 'name': 'Gen1OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gen1oftime": {'address': 8787, 'name': 'Gen1OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen2ofvalue": {'address': 8788, 'name': 'Gen2OFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gen2oftime": {'address': 8789, 'name': 'Gen2OFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen1ufvalue": {'address': 8790, 'name': 'Gen1UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gen1uftime": {'address': 8791, 'name': 'Gen1UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
    "gen2ufvalue": {'address': 8792, 'name': 'Gen2UFValue', 'precision': 2, 'index': 2, 'unit': 'Hz', 'device_class': 'frequency', 'state_class': 'measurement'},
    "gen2uftime": {'address': 8793, 'name': 'Gen2UFTime', 'precision': 2, 'index': 2, 'unit': 's', 'state_class': 'measurement'},
}

# Combined registers (post-process)
_COMBINED_REGISTERS_TREX_FIFTY = {
    "inverter_time": {
        "sources": ["time_year_month", "time_day_time", "time_minutes_seconds", "time_week"],
        "calc": lambda ym, dh, ms, w: {
            "year": 2000 + (ym >> 8),
            "month": ym & 0xFF,
            "day": dh >> 8,
            "hour": dh & 0xFF,
            "minute": ms >> 8,
            "second": ms & 0xFF,
            "weekday": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][w] if 0 <= w <= 6 else f"Unknown({w})",
            "iso_datetime": f"{2000 + (ym >> 8):04d}-{ym & 0xFF:02d}-{dh >> 8:02d} "
                            f"{dh & 0xFF:02d}:{ms >> 8:02d}:{ms & 0xFF:02d}",
        },
        "name": "Inverter Time",
    },
    "pv_power_kw": {
        "sources": ["pv1_power", "pv2_power", "pv3_power", "pv4_power"],
        "calc": lambda p1, p2, p3, p4: (p1 or 0) + (p2 or 0) + (p3 or 0) + (p4 or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Total PV Power kW",
        "precision": 1,
    },
    "total_pv_power": {
        "sources": ["pv1_power", "pv2_power", "pv3_power", "pv4_power"],
        "calc": lambda p1, p2, p3, p4: round(((p1 or 0) + (p2 or 0) + (p3 or 0) + (p4 or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "total_pv_power",
        "precision": 0,          # whole number only
    },
    "battery_power_kw": {
        "sources": ["bat1_power", "bat2_power"],
        "calc": lambda p1, p2: (p1 or 0) + (p2 or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Total Battery Power kW",
        "precision": 1,
    },
    "battery_power": { # we need this one in watts for the card
        "sources": ["bat1_power", "bat2_power"],
        "calc": lambda p1, p2: round(((p1 or 0) + (p2 or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Battery Power",
        "precision": 0,
    },
    "total_ac_output_active_power": { # legacy  naming trex-10
        "sources": ["phase_a_home_load_power", "phase_b_home_load_power", "phase_c_home_load_power"],
        "calc": lambda a, b, c: round(((a or 0) + (b or 0) + (c or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "total_ac_output_active_power",
        "precision": 0,
    },
    "generator_active_power_kw": {
        "sources": ["phase_a_generator_active_power", "phase_b_generator_active_power", "phase_c_generator_active_power"],
        "calc": lambda a, b, c: (a or 0) + (b or 0) + (c or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Generator Active Power kW",
        "precision": 1,
    },
    "grid_active_power_kw": {
        "sources": ["phase_a_grid_active_power", "phase_b_grid_active_power", "phase_c_grid_active_power"],
        "calc": lambda a, b, c: (a or 0) + (b or 0) + (c or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Grid Active Power kW",
        "precision": 1,
    },
    "ct_active_power_kw": {
        "sources": ["phase_a_ct_active_power", "phase_b_ct_active_power", "phase_c_ct_active_power"],
        "calc": lambda a, b, c: (a or 0) + (b or 0) + (c or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "CT Active Power kW",
        "precision": 1,
    },
    "total_ac_input_power": { # legacy naming trex 10
        "sources": ["phase_a_ct_active_power", "phase_b_ct_active_power", "phase_c_ct_active_power"],
        "calc": lambda a, b, c: round(((a or 0) + (b or 0) + (c or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "total_ac_input_power",
        "precision": 0,
    },
    "calculated_load_power_kw": {
        "sources": ["phase_a_ct_active_power", "phase_b_ct_active_power", "phase_c_ct_active_power", "total_grid_power"],
        "calc": lambda a, b, c, d: ((a or 0) + (b or 0) + (c or 0) - (d or 0)),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Caculated Load Power kW",
        "precision": 1,
    },
    "loadpower_lineside": { # legacy naming TREX
        "sources": ["phase_a_ct_active_power", "phase_b_ct_active_power", "phase_c_ct_active_power", "total_grid_power"],
        "calc": lambda a, b, c, d: round(((a or 0) + (b or 0) + (c or 0) - (d or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "loadpower_lineside",
        "precision": 0,
    },
    "inverter_active_power_kw": {
        "sources": ["phase_a_inverter_active_power", "phase_b_inverter_active_power", "phase_c_inverter_active_power"],
        "calc": lambda a, b, c: (a or 0) + (b or 0) + (c or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Inverter Active Power kW",
        "precision": 1,
    },    
    "load_active_power_kw": {
        "sources": ["phase_a_load_active_power", "phase_b_load_active_power", "phase_c_load_active_power"],
        "calc": lambda a, b, c: (a or 0) + (b or 0) + (c or 0),
        "unit": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Load Active Power kW",
        "precision": 1,
    },
    "total_generator_active_power": {
        "sources": ["phase_a_generator_active_power", "phase_b_generator_active_power", "phase_c_generator_active_power"],
        "calc": lambda a, b, c: round(((a or 0) + (b or 0) + (c or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Total Generator Active Power",
        "precision": 0,
    },
    "total_grid_active_power": {
        "sources": ["phase_a_grid_active_power", "phase_b_grid_active_power", "phase_c_grid_active_power"],
        "calc": lambda a, b, c: round(((a or 0) + (b or 0) + (c or 0)) * 1000),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Total Grid Active Power",
        "precision": 0,
    },
    "battery_voltage": {
        "sources": ["bat1_voltage", "bat2_voltage"],
        "calc": lambda v1, v2: (
            round((v1 + v2) / 2, 1) if v1 is not None and v2 is not None and v1 > 0 and v2 > 0
            else v1 if v1 is not None and v1 > 0
            else v2 if v2 is not None and v2 > 0
            else None
        ),
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "name": "Battery Voltage",
        "precision": 1,
    },
    "battery_current": {
        "sources": ["bat1_current", "bat2_current"],
        "calc": lambda c1, c2: round((c1 or 0) + (c2 or 0), 1),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "name": "Battery Current",
        "precision": 1,
    },
    "battery_capacity": {
        "sources": ["bat1_soc", "bat2_soc"],
        "calc": lambda s1, s2: (
            round((s1 + s2) / 2, 1) if s1 is not None and s2 is not None and s1 > 0 and s2 > 0
            else s1 if s1 is not None and s1 > 0
            else s2 if s2 is not None and s2 > 0
            else None
        ),
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "name": "Battery Capacity",
        "precision": 1,
    },
    "battery_discharge_depth_on_grid_bms": { # legacy naming
        "sources": ["soc_of_the_battery_low_alarm"],
        "calc": lambda s1: round(s1),
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "name": "battery_discharge_depth_on_grid_bms",
        "precision": 1,
    },
    # ECO rules (6, each with grid/gen enable, start/stop time, volt, soc, power)
    "econ_rule_1": {
        "sources": [
            "econ_rule_1_grid_charge_enable",
            "econ_rule_1_gen_charge_enable",
            "econ_rule_1_start_time",
            "econ_rule_1_stop_time",
            "econ_rule_1_voltage",
            "econ_rule_1_soc",
            "econ_rule_1_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 1",
    },
    "econ_rule_2": {
        "sources": [
            "econ_rule_2_grid_charge_enable",
            "econ_rule_2_gen_charge_enable",
            "econ_rule_2_start_time",
            "econ_rule_2_stop_time",
            "econ_rule_2_voltage",
            "econ_rule_2_soc",
            "econ_rule_2_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 2",
    },
    "econ_rule_3": {
        "sources": [
            "econ_rule_3_grid_charge_enable",
            "econ_rule_3_gen_charge_enable",
            "econ_rule_3_start_time",
            "econ_rule_3_stop_time",
            "econ_rule_3_voltage",
            "econ_rule_3_soc",
            "econ_rule_3_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 3",
    },
    "econ_rule_4": {
        "sources": [
            "econ_rule_4_grid_charge_enable",
            "econ_rule_4_gen_charge_enable",
            "econ_rule_4_start_time",
            "econ_rule_4_stop_time",
            "econ_rule_4_voltage",
            "econ_rule_4_soc",
            "econ_rule_4_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 4",
    },
    "econ_rule_5": {
        "sources": [
            "econ_rule_5_grid_charge_enable",
            "econ_rule_5_gen_charge_enable",
            "econ_rule_5_start_time",
            "econ_rule_5_stop_time",
            "econ_rule_5_voltage",
            "econ_rule_5_soc",
            "econ_rule_5_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 5",
    },
    "econ_rule_6": {
        "sources": [
            "econ_rule_6_grid_charge_enable",
            "econ_rule_6_gen_charge_enable",
            "econ_rule_6_start_time",
            "econ_rule_6_stop_time",
            "econ_rule_6_voltage",
            "econ_rule_6_soc",
            "econ_rule_6_power",
        ],
        "calc": lambda grid_en, gen_en, start_t, stop_t, volt, soc, power: {
            "grid_charge": "Enabled" if grid_en else "Disabled",
            "gen_charge": "Enabled" if gen_en else "Disabled",
            "start_time": f"{start_t >> 8:02d}:{start_t & 0xFF:02d}",
            "stop_time": f"{stop_t >> 8:02d}:{stop_t & 0xFF:02d}",
            "voltage_v": volt,
            "soc_value": soc,
            "power_kw": power,
        },
        "name": "Economic Mode Rule 6",
    },
}
REGISTER_SETS_TREX_FIFTY = {
    "basic": {
        key: info for key, info in _REGISTERS_TREX_FIFTY.items()
        if key in {
            "pv_total_power", "total_grid_power", "total_load_power", "battery_power",
            "inverter_time", "econ_rule_1", "econ_rule_2", "econ_rule_3",
            "econ_rule_4", "econ_rule_5", "econ_rule_6", "alarm_codes", "fault_codes",
            "phase_a_home_load_power", "phase_b_home_load_power", "phase_c_home_load_power",
            "generator_frequency", "grid_frequency", "load_frequency"
        }
    },
    "basic_plus": {
        key: info for key, info in _REGISTERS_TREX_FIFTY.items()
        if key.startswith(("pv", "phase_", "bat", "bus", "total_", "generator_", "grid_", "load_", "econ_rule_", "alarm", "fault"))
        and "_secondary" not in key
    },
    "full": _REGISTERS_TREX_FIFTY,
}
